language: python
python:
  - "3.4"
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls pytest-cov"
  - "pip install coverage --upgrade"
  - "python setup.py install"
script: PYTHONPATH=. py.test tests/ --cov EPPs --cov scripts --cov-report term-missing
after_success:
  - coveralls

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
